src/Entity/Cart.php
<?php

namespace App\Entity;

class Cart
{
    /**
     * @var CartItem[]
     */
    private array $items = [];

    public function addItem(CartItem $cartItem): CartItem
    {
        foreach ($this->items as $item) {
            if ($cartItem->matches($item)) {
                $item->increaseQuantity((int) $cartItem->getQuantity());

                return $item;
            }
        }

        $this->items[] = $cartItem;

        return $cartItem;
    }

    public function removeItem(CartItem $cartItem): void
    {
        foreach ($this->items as $key => $item) {
            if ($cartItem->matches($item)) {
                unset($this->items[$key]);
                $this->items = array_values($this->items);

                return;
            }
        }
    }

    public function getTotalString(): string
    {
        return (string) ($this->getTotal() / 100);
    }

    public function getTotal(): int
    {
        return array_reduce(
            $this->getItems(),
            static function ($accumulator, CartItem $item) {
                return $accumulator + $item->getTotal();
            },
            0
        );
    }

    /**
     * @return CartItem[]
     */
    public function getItems(): array
    {
        return $this->items;
    }

    public function countTotalItems(): int
    {
        return array_reduce(
            $this->getItems(),
            static function ($accumulator, CartItem $item) {
                return $accumulator + $item->getQuantity();
            },
            0
        );
    }

    public function hasItem(CartItem $cartItem): bool
    {
        return (bool) $this->findItem($cartItem->getProduct(), $cartItem->getColor());
    }

    public function findItem(Product $product, ?Color $color): ?CartItem
    {
        foreach ($this->items as $item) {
            if ($item->getProduct() === $product && $item->getColor() === $color) {
                return $item;
            }
        }

        return null;
    }
}

src/Entity/Color.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ColorRepository")
 */
class Color
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private string $name;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private string $hexColor;

    public function __construct(string $name, string $hexColor)
    {
        $this->name = $name;
        $this->hexColor = $hexColor;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHexColor(): ?string
    {
        return $this->hexColor;
    }

    public function setHexColor(string $hexColor): self
    {
        $this->hexColor = $hexColor;

        return $this;
    }

    public function getRed(): string
    {
        return (string) hexdec(substr($this->hexColor, 0, 2));
    }

    public function getGreen(): string
    {
        return (string) hexdec(substr($this->hexColor, 2, 2));
    }

    public function getBlue(): string
    {
        return (string) hexdec(substr($this->hexColor, 4, 2));
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups("product:read")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("product:read")
     * @Assert\NotBlank()
     */
    private ?string $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("product:read")
     */
    private ?string $description;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank
     */
    private string $brand = 'Low End Luxury';

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private ?float $weight = null;

    /**
     * @ORM\Column(type="integer")
     * @Groups("product:read")
     * @Assert\GreaterThan(0)
     * @Assert\NotBlank()
     */
    private int $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(0)
     */
    private int $stockQuantity = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private ?Category $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Color")
     */
    private Collection $colors;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private string $imageFilename = 'floppy-disc.png';

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="product", cascade={"remove"})
     */
    private Collection $reviews;

    public function __construct()
    {
        $this->colors = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStockQuantity(): ?int
    {
        return $this->stockQuantity;
    }

    public function setStockQuantity(int $stockQuantity): self
    {
        $this->stockQuantity = $stockQuantity;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Color[]
     */
    public function getColors(): Collection
    {
        return $this->colors;
    }

    public function addColor(Color $color): self
    {
        if (!$this->colors->contains($color)) {
            $this->colors[] = $color;
        }

        return $this;
    }

    public function removeColor(Color $color): self
    {
        if ($this->colors->contains($color)) {
            $this->colors->removeElement($color);
        }

        return $this;
    }

    public function hasColors(): bool
    {
        return count($this->colors) > 0;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    /**
     * @Groups("product:read")
     */
    public function getImageUrl(): string
    {
        return sprintf('/uploads/products/'.$this->imageFilename);
    }

    public function getAverageStars(): float
    {
        if (0 === count($this->getReviews())) {
            return 0;
        }

        $totalRating = 0;
        // this is an inefficient way of doing this ;)
        foreach ($this->getReviews() as $review) {
            $totalRating += $review->getStars();
        }

        return round($totalRating / count($this->getReviews()), 1);
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function __toString(): string
    {
        return sprintf('%s ($%s)', $this->name, $this->getPriceString());
    }

    public function getPriceString(): string
    {
        return (string) ($this->price / 100);
    }
}

src/Controller/CartController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Color;
use App\Entity\Product;
use App\Form\AddItemToCartFormType;
use App\Repository\CategoryRepository;
use App\Repository\ColorRepository;
use App\Repository\ProductRepository;
use App\Service\CartStorage;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Annotation\Route;

final class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="app_cart")
     */
    public function shoppingCart(CartStorage $cartStorage): Response
    {
        return $this->renderForm(
            'cart/cart.html.twig',
            [
                'cart' => $cartStorage->getOrCreateCart(),
            ]
        );
    }

    #[Route('/cart/_featured', name: 'app_cart_product_featured')]
    public function _cartFeaturedProduct(
        Request $request,
        ProductRepository $productRepository
    ): Response {
        $featuredProduct = $productRepository->findFeatured();
        $addToCartForm = $this->createForm(
            AddItemToCartFormType::class,
            null,
            [
                'product' => $featuredProduct,
            ]
        );

        return $this->renderForm(
            'cart/_featuredSidebar.html.twig',
            [
                'addToCartForm' => $addToCartForm,
                'featuredProduct' => $featuredProduct,
                'showDescription' => $request->query->get('description'),
            ]
        );
    }

    /**
     * @Route("/cart/_list", name="_app_cart_list")
     */
    public function _shoppingCartList(CartStorage $cartStorage): Response
    {
        return $this->render(
            'cart/_cartList.html.twig',
            [
                'cart' => $cartStorage->getOrCreateCart(),
            ]
        );
    }

    /**
     * @Route("/product/{id}/cart", name="app_cart_add_item", methods={"POST"})
     */
    public function addItemToCart(
        Product $product,
        Request $request,
        CategoryRepository $categoryRepository,
        CartStorage $cartStorage
    ): Response {
        $addToCartForm = $this->createForm(
            AddItemToCartFormType::class,
            null,
            [
                'product' => $product,
            ]
        );

        $addToCartForm->handleRequest($request);
        if ($addToCartForm->isSubmitted() && $addToCartForm->isValid()) {
            $cart = $cartStorage->getOrCreateCart();
            $cart->addItem($addToCartForm->getData());
            $cartStorage->save($cart);

            $this->addFlash('success', 'Item added!');

            return $this->redirectToRoute(
                'app_product',
                [
                    'id' => $product->getId(),
                ]
            );
        }

        return $this->renderForm(
            'product/show.html.twig',
            [
                'product' => $product,
                'categories' => $categoryRepository->findAll(),
                'addToCartForm' => $addToCartForm,
            ]
        );
    }

    /**
     * @Route("/cart/remove/{productId}/{colorId?}", name="app_cart_remove_item", methods={"POST"})
     */
    public function removeItemToCart(
        int $productId,
        int $colorId,
        Request $request,
        CartStorage $cartStorage,
        ProductRepository $productRepository,
        ColorRepository $colorRepository
    ): Response {
        /** @var Product|null $product */
        $product = $productRepository->find($productId);
        /** @var Color|null $color */
        $color = $colorId ? $colorRepository->find($colorId) : null;

        if (!$product) {
            $this->createNotFoundException();
        }

        if (!$this->isCsrfTokenValid('remove_item', (string) $request->request->get('_token'))) {
            throw new BadRequestHttpException('Invalid CSRF token');
        }

        $cart = $cartStorage->getOrCreateCart();
        $cartItem = $cart->findItem($product, $color);
        if ($cartItem) {
            $cart->removeItem($cartItem);
        }
        $cartStorage->save($cart);

        $this->addFlash('success', 'Item removed!');

        return $this->redirectToRoute('app_cart');
    }
}

templates/cart/_cartList.html.twig
<div>
    <div class="row p-3">
        <div class="col-3 fw-bold">
            Item Name
        </div>
        <div class="col-3 fw-bold">
            Quantity
        </div>
        <div class="col-3 fw-bold">
            Price
        </div>
        <div class="col-3"></div>
    </div>
    {% for item in cart.items %}
        <div
            class="cart-item row p-3"
            data-action="submit-confirm:async:submitted->reload-content#refreshContent"
        >
            <div class="col-2">
                {{ item.product.name }}
            </div>
            <div class="col-1">
                {% if item.color %}
                    <span class="color-square" style="background-color: rgb({{ item.color.red }}, {{ item.color.green }}, {{ item.color.blue }});"></span>
                {% endif %}
            </div>
            <div class="col-3">
                {{ item.quantity }}
            </div>
            <div class="col-3">
                {{ item.totalString|format_currency('USD') }}
            </div>
            <div class="col-3">
                <form
                    action="{{ path('app_cart_remove_item', {
                        productId: item.product.id,
                        colorId: item.color ? item.color.id: null,
                    }) }}"
                    method="POST"
                    {{ stimulus_controller('submit-confirm', {
                        title: 'Remove this item?',
                        icon: 'warning',
                        confirmButtonText: 'Yes, remove it',
                        submitAsync: true,
                    }) }}
                    data-action="submit-confirm#onSubmit"
                >
                    <input type="hidden" name="_token" value="{{ csrf_token('remove_item') }}" />

                    <button class="btn btn-info btn-sm">
                        Remove
                    </button>
                </form>
            </div>
        </div>
    {% else %}
        <div class="col text-center mt-5">
            Your cart is empty! <a href="{{ path('app_homepage') }}">Get to shopping!</a>
        </div>
    {% endfor %}

    {% if cart.items|length > 0 %}
    <div class="p-3">
        Total: <strong>{{ cart.totalString|format_currency('USD') }}</strong>
    </div>
    {% endif %}
</div>

{% if cart.items|length > 0 %}
<div>
    <a href="{{ path('app_checkout') }}" class="btn btn-primary">
        Check Out &gt;&gt;
    </a>
</div>
{% endif %}

templates/cart/_featuredSidebar.html.twig
<turbo-frame id="cart-sidebar" target="_top">
    <div class="component-light product-show p-3 mb-5">
        <h5 class="text-center">Featured Product!</h5>
        <a href="{{ path('app_product', { id: featuredProduct.id }) }}">
            <img alt="{{ featuredProduct.name }}"
                 src="{{ asset('/uploads/products/'~featuredProduct.imageFilename) }}"
                 class="d-block">
        </a>
        <div class="pt-3">
            <h6 class="d-flex justify-content-between mb-3">
                <strong>{{ featuredProduct.name }}</strong>
                {{ featuredProduct.priceString|format_currency('USD') }}
            </h6>
            {% if showDescription %}
                {{ featuredProduct.description }}
            {% else %}
                {{ featuredProduct.description|u.truncate(25)|trim }}...
                <a href="{{ path('app_cart_product_featured',{description:true}) }}"
                   data-turbo-frame="cart-sidebar"
                   class="frame-loading-hide">
                    (read more)
                </a>
                <span class="frame-loading-show fas fa-spinner fa-spin"></span>
            {% endif %}
            {{ include('product/_cart_add_controls.html.twig') }}
        </div>
    </div>
</turbo-frame>

templates/cart/cart.html.twig
{% extends 'base.html.twig' %}

{% block metas %}
    {{ parent() }}
    <link rel="prefetch" href="{{ path('app_checkout') }}">
{% endblock %}

{% block body %}
    <div class="container-fluid container-xl mt-4">
        <div class="row">
            <aside class="col-12 col-md-4 order-2 order-md-1">
                <turbo-frame id="cart-sidebar"
                             src="{{ path('app_cart_product_featured') }}"
                             target="_top">
                    Loading...
                </turbo-frame>
            </aside>
            <div class="col-12 col-md-8 order-1 order-md-2 cart">
                <h1>Shopping Cart</h1>
                <div class="p-3"
                        {{ stimulus_controller('reload-content', {
                            url: path('_app_cart_list')
                        }) }}>
                    {{ include('cart/_cartList.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}