src/Entity/Review.php
<?php

namespace App\Entity;

use App\Repository\ReviewRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\UX\Turbo\Attribute\Broadcast;

/**
 * @ORM\Entity(repositoryClass=ReviewRepository::class)
 */
#[Broadcast]
class Review
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Tell us what you thought about the product")
     * @Assert\Length(min="20", minMessage="Please tell us a bit more!")
     */
    private string $content;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private User $owner;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private Product $product;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(1, message="It sounds terrible! But 1 is the minimum rating.")
     * @Assert\LessThanOrEqual(5, message="I'm glad you love it! But 5 is the max rating.")
     * @Assert\NotBlank(message="Please rate this!")
     */
    private ?int $stars;

    public function __construct(User $owner, Product $product)
    {
        $this->owner = $owner;
        $this->product = $product;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function getContentPreview(): string
    {
        if (strlen($this->content) < 50) {
            return $this->content;
        }

        return substr($this->content, 0, 50).'...';
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getOwner(): User
    {
        return $this->owner;
    }

    public function getProduct(): Product
    {
        return $this->product;
    }

    public function getStars(): ?int
    {
        return $this->stars;
    }

    public function setStars(?int $stars): self
    {
        $this->stars = $stars;

        return $this;
    }
}

src/Controller/ReviewAdminController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Review;
use App\Form\ReviewType;
use App\Repository\ReviewRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/review")
 */
final class ReviewAdminController extends AbstractController
{
    /**
     * @Route("/", name="review_admin_index", methods={"GET"})
     */
    public function index(ReviewRepository $reviewRepository): Response
    {
        return $this->render(
            'review_admin/index.html.twig',
            [
                'reviews' => $reviewRepository->findBy([], ['id' => 'DESC']),
            ]
        );
    }

    /**
     * @Route("/new", name="review_admin_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $review = new Review();
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($review);
            $entityManager->flush();

            return $this->redirectToRoute('review_admin_index');
        }

        return $this->renderForm(
            'review_admin/new.html.twig',
            [
                'review' => $review,
                'form' => $form,
            ]
        );
    }

    /**
     * @Route("/{id}/edit", name="review_admin_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Review $review): Response
    {
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('review_admin_index');
        }

        return $this->renderForm(
            'review_admin/edit.html.twig',
            [
                'review' => $review,
                'form' => $form,
            ]
        );
    }

    /**
     * @Route("/{id}", name="review_admin_delete", methods={"POST"})
     */
    public function delete(Request $request, Review $review): Response
    {
        if ($this->isCsrfTokenValid('delete'.$review->getId(), (string) $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($review);
            $entityManager->flush();
        }

        return $this->redirectToRoute('review_admin_index');
    }
}

templates/review_admin/_delete_form.html.twig
<form class="mt-2" method="post" action="{{ path('review_admin_delete', {'id': review.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ review.id) }}">
    <button class="btn btn-danger btn-sm">Delete</button>
</form>

templates/review_admin/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/review_admin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Review{% endblock %}

{% block body %}
<div class="container mt-4">
    <a href="{{ path('review_admin_index') }}"><i class="fas fa-caret-left"></i> back to list</a>
    <div class="d-flex justify-content-between">
        <h1 class="mt-3">Edit Review</h1>
        {{ include('review_admin/_delete_form.html.twig') }}
    </div>

    {{ include('review_admin/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('review_admin/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/review_admin/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review index{% endblock %}

{% block body %}
<div class="container-fluid container-xl mt-4">
    <h1>Review index</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Comment</th>
                    <th>Product</th>
                    <th>Stars</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for review in reviews %}
                <tr>
                    <td>{{ review.contentPreview }}</td>
                    <td>{{ review.product.name }}</td>
                    <td>{{ review.stars }}</td>
                    <td>
                        <a href="{{ path('review_admin_edit', {'id': review.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{ path('review_admin_new') }}">Create new</a>
</div>
{% endblock %}

templates/review_admin/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Review{% endblock %}

{% block body %}
<div class="container-fluid mt-4">
    <h1>Create new Review</h1>

    {{ include('review_admin/_form.html.twig') }}

    <a href="{{ path('review_admin_index') }}">back to list</a>
</div>
{% endblock %}